dist: trusty
language: python
matrix:
  include:
    - python: "3.10"
      env: TEST_SUITE=suite_3_10
install:
  - if [[ $TEST_SUITE == suite_3_10 ]]; then
        pip install sphinx;
    fi;
  - pip install coverage
  - pip install -r requirements.txt
  - python setup.py install
script:
  - nosetests --with-coverage  --cover-erase --cover-package=oospectro
  - if [[ $TEST_SUITE == suite_3_10 ]]; then
        cd doc;
        make html;
    fi;

after_success:
  - pip install coveralls
  - coveralls
